import { describe, expect, it } from "vitest";
import { parseServerConfig } from "./config";

const validEnvironment = {
  KV_REST_API_URL: "https://example.upstash.io",
  KV_REST_API_TOKEN: "secret",
  RATAPP_REDIS_KEY_PREFIX: "ratapp:test:unit",
  NODE_ENV: "test",
} as const;

describe("parseServerConfig", () => {
  it("applies the Phase 5 defaults", () => {
    expect(parseServerConfig(validEnvironment)).toMatchObject({
      sessionTtlSeconds: 86_400,
      maxExpensesPerSession: 100,
      useSeededSession: false,
      environment: "test",
    });
  });

  it.each([
    { ...validEnvironment, KV_REST_API_URL: "http://example.test" },
    { ...validEnvironment, KV_REST_API_TOKEN: "" },
    { ...validEnvironment, RATAPP_REDIS_KEY_PREFIX: "unsafe*" },
    { ...validEnvironment, RATAPP_SESSION_TTL_SECONDS: "0" },
    { ...validEnvironment, RATAPP_MAX_EXPENSES_PER_SESSION: "1.5" },
  ])("rejects unsafe configuration", (environment) => {
    expect(() => parseServerConfig(environment)).toThrow();
  });

  it("rejects seeded-session mode in production", () => {
    expect(() =>
      parseServerConfig({
        ...validEnvironment,
        NODE_ENV: "production",
        RATAPP_USE_SEEDED_SESSION: "true",
      }),
    ).toThrow(/forbidden/i);
  });

  it("accepts the server-only names generated by a prefixed Vercel integration", () => {
    const { KV_REST_API_URL, KV_REST_API_TOKEN, ...rest } = validEnvironment;
    expect(
      parseServerConfig({
        ...rest,
        REDIS_KV_REST_API_URL: KV_REST_API_URL,
        REDIS_KV_REST_API_TOKEN: KV_REST_API_TOKEN,
      }),
    ).toMatchObject({
      redisUrl: KV_REST_API_URL,
      redisToken: KV_REST_API_TOKEN,
    });
  });
});
