import { describe, expect, it } from "vitest";
import { OPEN_ROUTER_MODEL, parseAiConfig, parseServerConfig } from "./config";

const validEnvironment = {
  KV_REST_API_URL: "https://example.upstash.io",
  KV_REST_API_TOKEN: "secret",
  RATAPP_REDIS_KEY_PREFIX: "ratapp:test:unit",
  NODE_ENV: "test",
} as const;

describe("parseServerConfig", () => {
  it("applies the Phase 5 defaults", () => {
    expect(parseServerConfig(validEnvironment)).toMatchObject({
      sessionTtlSeconds: 172_800,
      maxExpensesPerSession: 100,
      environment: "test",
    });
  });

  it.each([
    { ...validEnvironment, KV_REST_API_URL: "http://example.test" },
    { ...validEnvironment, KV_REST_API_TOKEN: "" },
    { ...validEnvironment, RATAPP_REDIS_KEY_PREFIX: "unsafe*" },
    { ...validEnvironment, RATAPP_SESSION_TTL_SECONDS: "0" },
    { ...validEnvironment, RATAPP_MAX_EXPENSES_PER_SESSION: "1.5" },
  ])("rejects unsafe configuration", (environment) => {
    expect(() => parseServerConfig(environment)).toThrow();
  });

  it("accepts the server-only names generated by a prefixed Vercel integration", () => {
    const { KV_REST_API_URL, KV_REST_API_TOKEN, ...rest } = validEnvironment;
    expect(
      parseServerConfig({
        ...rest,
        REDIS_KV_REST_API_URL: KV_REST_API_URL,
        REDIS_KV_REST_API_TOKEN: KV_REST_API_TOKEN,
      }),
    ).toMatchObject({
      redisUrl: KV_REST_API_URL,
      redisToken: KV_REST_API_TOKEN,
    });
  });
});

describe("parseAiConfig", () => {
  it("validates AI settings independently from Redis settings", () => {
    expect(
      parseAiConfig({
        OPENROUTER_API_KEY: "test-only-key",
        OPEN_ROUTER_MODEL: OPEN_ROUTER_MODEL,
      }),
    ).toEqual({ apiKey: "test-only-key", models: [OPEN_ROUTER_MODEL] });
    expect(() => parseServerConfig(validEnvironment)).not.toThrow();
  });

  it("parses and trims an ordered model fallback list", () => {
    expect(
      parseAiConfig({
        OPENROUTER_API_KEY: "test-only-key",
        OPEN_ROUTER_MODEL: "provider/primary, provider/fallback ,third/model",
      }),
    ).toEqual({
      apiKey: "test-only-key",
      models: ["provider/primary", "provider/fallback", "third/model"],
    });
  });

  it.each([
    {},
    { OPENROUTER_API_KEY: "" },
    {
      OPENROUTER_API_KEY: "replace-with-a-key",
      OPEN_ROUTER_MODEL: OPEN_ROUTER_MODEL,
    },
    { OPENROUTER_API_KEY: "test-only-key", OPEN_ROUTER_MODEL: "" },
    { OPENROUTER_API_KEY: "test-only-key", OPEN_ROUTER_MODEL: ",other/model" },
    { OPENROUTER_API_KEY: "test-only-key", OPEN_ROUTER_MODEL: "other/model," },
    {
      OPENROUTER_API_KEY: "test-only-key",
      OPEN_ROUTER_MODEL: "primary/model, ,fallback/model",
    },
  ])("rejects incomplete or unsafe AI settings", (environment) => {
    expect(() => parseAiConfig(environment)).toThrow();
  });
});
