import { describe, expect, it } from "vitest";
import { OPENAI_MODEL, parseAiConfig, parseServerConfig } from "./config";

const validEnvironment = {
  KV_REST_API_URL: "https://example.upstash.io",
  KV_REST_API_TOKEN: "secret",
  RATAPP_REDIS_KEY_PREFIX: "ratapp:test:unit",
  NODE_ENV: "test",
} as const;

describe("parseServerConfig", () => {
  it("applies the Phase 5 defaults", () => {
    expect(parseServerConfig(validEnvironment)).toMatchObject({
      sessionTtlSeconds: 172_800,
      maxExpensesPerSession: 100,
      environment: "test",
    });
  });

  it.each([
    { ...validEnvironment, KV_REST_API_URL: "http://example.test" },
    { ...validEnvironment, KV_REST_API_TOKEN: "" },
    { ...validEnvironment, RATAPP_REDIS_KEY_PREFIX: "unsafe*" },
    { ...validEnvironment, RATAPP_SESSION_TTL_SECONDS: "0" },
    { ...validEnvironment, RATAPP_MAX_EXPENSES_PER_SESSION: "1.5" },
  ])("rejects unsafe configuration", (environment) => {
    expect(() => parseServerConfig(environment)).toThrow();
  });

  it("accepts the server-only names generated by a prefixed Vercel integration", () => {
    const { KV_REST_API_URL, KV_REST_API_TOKEN, ...rest } = validEnvironment;
    expect(
      parseServerConfig({
        ...rest,
        REDIS_KV_REST_API_URL: KV_REST_API_URL,
        REDIS_KV_REST_API_TOKEN: KV_REST_API_TOKEN,
      }),
    ).toMatchObject({
      redisUrl: KV_REST_API_URL,
      redisToken: KV_REST_API_TOKEN,
    });
  });
});

describe("parseAiConfig", () => {
  it("validates AI settings independently from Redis settings", () => {
    expect(
      parseAiConfig({
        OPENAI_API_KEY: "test-only-key",
        OPENAI_MODEL,
      }),
    ).toEqual({ apiKey: "test-only-key", model: OPENAI_MODEL });
    expect(() => parseServerConfig(validEnvironment)).not.toThrow();
  });

  it("trims the configured model", () => {
    expect(
      parseAiConfig({
        OPENAI_API_KEY: "test-only-key",
        OPENAI_MODEL: "  gpt-4.1-nano  ",
      }),
    ).toEqual({
      apiKey: "test-only-key",
      model: "gpt-4.1-nano",
    });
  });

  it.each([
    {},
    { OPENAI_API_KEY: "" },
    {
      OPENAI_API_KEY: "replace-with-a-key",
      OPENAI_MODEL,
    },
    { OPENAI_API_KEY: "test-only-key", OPENAI_MODEL: "" },
    { OPENAI_API_KEY: "test-only-key", OPENAI_MODEL: "   " },
  ])("rejects incomplete or unsafe AI settings", (environment) => {
    expect(() => parseAiConfig(environment)).toThrow();
  });
});
